aurora_sensor:
  marker: [
    {
      rom_id: 0,
      name: Ultrasonic
    },
    {
      rom_id: 1,
      name: Probe
    },
    {
      rom_id: 2,
      name: UR_Robot
    },
    {
      rom_id: 3,
      name: Aim_Track
    }
  ]