aurora_sensor:
  marker: [
    {
      id: 10,
      name: Ultrasonic
    },
    {
      id: 11,
      name: Probe
    },
    {
      id: 12,
      name: UR_Robot
    },
    {
      id: 13,
      name: Aim_Track
    },
  ]